import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parse } from '../parser/parser';
import { emit, DEFAULT_CONFIG, CodeGenConfig } from '../codegen/emitter';

function generate(proto: string, config?: Partial<CodeGenConfig>): string {
  const file = parse(proto);
  return emit(file, { ...DEFAULT_CONFIG, ...config });
}

test('basic message → interface with camelCase fields', () => {
  const out = generate(`
    syntax = "proto3";
    message User {
      string user_name = 1;
      int32 user_age = 2;
      bool is_active = 3;
    }
  `);
  assert.ok(out.includes('export interface User {'));
  assert.ok(out.includes('  userName: string;'));
  assert.ok(out.includes('  userAge: number;'));
  assert.ok(out.includes('  isActive: boolean;'));
});

test('fieldNaming preserve keeps snake_case', () => {
  const out = generate(`
    syntax = "proto3";
    message User {
      string user_name = 1;
    }
  `, { fieldNaming: 'preserve' });
  assert.ok(out.includes('  user_name: string;'));
});

test('message field is optional by default', () => {
  const out = generate(`
    syntax = "proto3";
    message Order {
      Address shipping = 1;
    }
    message Address {
      string street = 1;
    }
  `);
  assert.ok(out.includes('  shipping?: Address;'));
});

test('optionalMessageFields false removes ?', () => {
  const out = generate(`
    syntax = "proto3";
    message Order {
      Address shipping = 1;
    }
    message Address {
      string street = 1;
    }
  `, { optionalMessageFields: false });
  assert.ok(out.includes('  shipping: Address;'));
});

test('optionalScalarFields true adds ? to scalars', () => {
  const out = generate(`
    syntax = "proto3";
    message Foo {
      string name = 1;
    }
  `, { optionalScalarFields: true });
  assert.ok(out.includes('  name?: string;'));
});

test('repeated field → T[]', () => {
  const out = generate(`
    syntax = "proto3";
    message Foo {
      repeated string tags = 1;
      repeated int32 ids = 2;
    }
  `);
  assert.ok(out.includes('  tags: string[];'));
  assert.ok(out.includes('  ids: number[];'));
});

test('map field → Record<K, V>', () => {
  const out = generate(`
    syntax = "proto3";
    message Foo {
      map<string, int32> limits = 1;
    }
  `);
  assert.ok(out.includes('  limits: Record<string, number>;'));
});

test('enum style: TS enum (default)', () => {
  const out = generate(`
    syntax = "proto3";
    enum Status {
      UNKNOWN = 0;
      ACTIVE = 1;
      INACTIVE = 2;
    }
  `);
  assert.ok(out.includes('export enum Status {'));
  assert.ok(out.includes('  UNKNOWN = 0,'));
  assert.ok(out.includes('  ACTIVE = 1,'));
  assert.ok(out.includes('  INACTIVE = 2,'));
});

test('enum style: union', () => {
  const out = generate(`
    syntax = "proto3";
    enum Status {
      UNKNOWN = 0;
      ACTIVE = 1;
    }
  `, { enumStyle: 'union' });
  assert.ok(out.includes("export type Status = 'UNKNOWN' | 'ACTIVE';"));
});

test('oneof style: optional (default)', () => {
  const out = generate(`
    syntax = "proto3";
    message Result {
      string id = 1;
      oneof value {
        string error = 2;
        int32 count = 3;
      }
    }
  `);
  assert.ok(out.includes('export interface Result {'));
  assert.ok(out.includes('  error?: string;'));
  assert.ok(out.includes('  count?: number;'));
});

test('oneof style: union', () => {
  const out = generate(`
    syntax = "proto3";
    message Result {
      oneof value {
        string error = 1;
        int32 count = 2;
      }
    }
  `, { oneofStyle: 'union' });
  assert.ok(out.includes('export type Result ='));
  assert.ok(out.includes('error: string'));
  assert.ok(out.includes('count?: never'));
});

test('nested message and enum', () => {
  const out = generate(`
    syntax = "proto3";
    message Outer {
      message Inner {
        string id = 1;
      }
      enum Kind {
        A = 0;
        B = 1;
      }
      Inner inner = 1;
      Kind kind = 2;
    }
  `);
  assert.ok(out.includes('export interface Inner {'));
  assert.ok(out.includes('export enum Kind {'));
  assert.ok(out.includes('export interface Outer {'));
});

test('bytes maps to Uint8Array', () => {
  const out = generate(`
    syntax = "proto3";
    message Foo {
      bytes data = 1;
    }
  `);
  assert.ok(out.includes('  data: Uint8Array;'));
});

test('header comment present', () => {
  const out = generate(`
    syntax = "proto3";
    message Foo {
      string x = 1;
    }
  `);
  assert.ok(out.startsWith('// Generated by proto-utils. Do not edit.'));
});

test('cross-file import generation', () => {
  const file = parse(`
    syntax = "proto3";
    message Order {
      Address shipping = 1;
    }
  `);
  const resolver = (typeName: string) => typeName === 'Address' ? 'common/address.proto' : null;
  const out = emit(file, DEFAULT_CONFIG, resolver);
  assert.ok(out.includes("import type { Address } from './common/address';"));
  assert.ok(out.includes('  shipping?: Address;'));
});

test('empty message', () => {
  const out = generate(`
    syntax = "proto3";
    message Empty {}
  `);
  assert.ok(out.includes('export interface Empty {'));
  assert.ok(out.includes('}'));
});
