import * as ast from '../parser/ast';

export interface CodeGenConfig {
  enumStyle: 'enum' | 'union';
  optionalMessageFields: boolean;
  optionalScalarFields: boolean;
  fieldNaming: 'camelCase' | 'preserve';
  oneofStyle: 'optional' | 'union';
}

export const DEFAULT_CONFIG: CodeGenConfig = {
  enumStyle: 'enum',
  optionalMessageFields: true,
  optionalScalarFields: false,
  fieldNaming: 'camelCase',
  oneofStyle: 'optional',
};

const SCALAR_MAP: Record<string, string> = {
  double: 'number', float: 'number',
  int32: 'number', int64: 'number',
  uint32: 'number', uint64: 'number',
  sint32: 'number', sint64: 'number',
  fixed32: 'number', fixed64: 'number',
  sfixed32: 'number', sfixed64: 'number',
  bool: 'boolean', string: 'string', bytes: 'Uint8Array',
};

const SCALAR_TYPES = new Set(Object.keys(SCALAR_MAP));

/**
 * Resolve a type name to the proto file path it's defined in (for import generation).
 * Return null if the type is local (same file) or scalar.
 */
export type TypeResolver = (typeName: string) => string | null;

export function emit(file: ast.ProtoFile, config: CodeGenConfig, resolve?: TypeResolver): string {
  const imports = new Map<string, Set<string>>(); // protoPath → type names
  const lines: string[] = [];

  lines.push('// Generated by proto-utils. Do not edit.');
  lines.push('');

  for (const def of file.definitions) {
    if (def.kind === 'message') emitMessage(def, config, resolve, imports, lines, '');
    else if (def.kind === 'enum') emitEnum(def, config, lines, '');
    // services are skipped (out of scope for type generation)
  }

  // Build import statements
  const importLines: string[] = [];
  if (resolve && imports.size > 0) {
    for (const [protoPath, typeNames] of imports) {
      const tsPath = protoPath.replace(/\.proto$/, '');
      const names = [...typeNames].sort();
      importLines.push(`import type { ${names.join(', ')} } from './${tsPath}';`);
    }
    importLines.push('');
  }

  // Combine: header + imports + body
  const header = lines.slice(0, 2);
  const body = lines.slice(2);
  return [...header, ...importLines, ...body].join('\n').trimEnd() + '\n';
}

// ─── Helpers ─────────────────────────────────────────────────

function toCamelCase(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

function fieldName(name: string, config: CodeGenConfig): string {
  return config.fieldNaming === 'camelCase' ? toCamelCase(name) : name;
}

function isScalar(typeName: string): boolean {
  return SCALAR_TYPES.has(typeName);
}

function tsType(typeName: string): string {
  return SCALAR_MAP[typeName] ?? typeName;
}

function trackImport(typeName: string, resolve: TypeResolver | undefined, imports: Map<string, Set<string>>): void {
  if (!resolve || isScalar(typeName)) return;
  const baseName = typeName.includes('.') ? typeName.split('.').pop()! : typeName;
  const protoPath = resolve(typeName);
  if (protoPath) {
    if (!imports.has(protoPath)) imports.set(protoPath, new Set());
    imports.get(protoPath)!.add(baseName);
  }
}

// ─── Emitters ────────────────────────────────────────────────

function emitMessage(
  msg: ast.MessageDef,
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
  lines: string[],
  indent: string,
): void {
  // Nested enums first
  for (const nested of msg.nestedEnums) {
    emitEnum(nested, config, lines, indent);
    lines.push('');
  }
  // Nested messages
  for (const nested of msg.nestedMessages) {
    emitMessage(nested, config, resolve, imports, lines, indent);
    lines.push('');
  }

  // Handle oneof as union type
  if (config.oneofStyle === 'union' && msg.oneofs.length > 0) {
    emitMessageWithUnionOneof(msg, config, resolve, imports, lines, indent);
    return;
  }

  lines.push(`${indent}export interface ${msg.name.name} {`);

  for (const field of msg.fields) {
    emitField(field, config, resolve, imports, lines, indent + '  ');
  }

  // Oneof fields as optional
  for (const oneof of msg.oneofs) {
    for (const field of oneof.fields) {
      const name = fieldName(field.name.name, config);
      const type = resolveFieldType(field.type.name, config, resolve, imports);
      lines.push(`${indent}  ${name}?: ${type};`);
    }
  }

  lines.push(`${indent}}`);
  lines.push('');
}

function emitMessageWithUnionOneof(
  msg: ast.MessageDef,
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
  lines: string[],
  indent: string,
): void {
  // Regular fields as a base interface
  const regularFields: string[] = [];
  for (const field of msg.fields) {
    regularFields.push(renderField(field, config, resolve, imports));
  }

  // Build union members for each oneof
  for (const oneof of msg.oneofs) {
    const variants: string[] = [];
    for (const field of oneof.fields) {
      const name = fieldName(field.name.name, config);
      const type = resolveFieldType(field.type.name, config, resolve, imports);
      // This variant has this field set, others in the oneof are never
      const othersNever = oneof.fields
        .filter(f => f !== field)
        .map(f => `${fieldName(f.name.name, config)}?: never`)
        .join('; ');
      variants.push(`{ ${name}: ${type}; ${othersNever} }`);
    }

    if (regularFields.length > 0) {
      lines.push(`${indent}export type ${msg.name.name} = (${regularFields.join(' & ')}) & (`);
      lines.push(`${indent}  | ${variants.join(`\n${indent}  | `)}`);
      lines.push(`${indent});`);
    } else {
      lines.push(`${indent}export type ${msg.name.name} =`);
      lines.push(`${indent}  | ${variants.join(`\n${indent}  | `)};`);
    }
    lines.push('');
  }

  // If no oneofs (shouldn't reach here, but safety)
  if (msg.oneofs.length === 0) {
    lines.push(`${indent}export interface ${msg.name.name} {`);
    for (const field of msg.fields) {
      emitField(field, config, resolve, imports, lines, indent + '  ');
    }
    lines.push(`${indent}}`);
    lines.push('');
  }
}

function emitField(
  field: ast.FieldDef,
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
  lines: string[],
  indent: string,
): void {
  lines.push(`${indent}${renderField(field, config, resolve, imports)};`);
}

function renderField(
  field: ast.FieldDef,
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
): string {
  if (field.kind === 'map') {
    trackImport(field.valueType.name, resolve, imports);
    const key = tsType(field.keyType.name);
    const val = resolveFieldType(field.valueType.name, config, resolve, imports);
    const name = fieldName(field.name.name, config);
    return `${name}: Record<${key}, ${val}>`;
  }

  const name = fieldName(field.name.name, config);
  const typeName = field.type.name;
  trackImport(typeName, resolve, imports);

  if (field.label === 'repeated') {
    const type = resolveFieldType(typeName, config, resolve, imports);
    return `${name}: ${type}[]`;
  }

  const scalar = isScalar(typeName);
  const optional = scalar ? config.optionalScalarFields : config.optionalMessageFields;
  const type = resolveFieldType(typeName, config, resolve, imports);
  return `${name}${optional ? '?' : ''}: ${type}`;
}

function resolveFieldType(
  typeName: string,
  _config: CodeGenConfig,
  _resolve: TypeResolver | undefined,
  _imports: Map<string, Set<string>>,
): string {
  if (isScalar(typeName)) return SCALAR_MAP[typeName];
  // For cross-file types, use the base name (import handles the rest)
  return typeName.includes('.') ? typeName.split('.').pop()! : typeName;
}

function emitEnum(
  e: ast.EnumDef,
  config: CodeGenConfig,
  lines: string[],
  indent: string,
): void {
  if (config.enumStyle === 'union') {
    const members = e.values.map(v => `'${v.name.name}'`).join(' | ');
    lines.push(`${indent}export type ${e.name.name} = ${members};`);
  } else {
    lines.push(`${indent}export enum ${e.name.name} {`);
    for (const v of e.values) {
      lines.push(`${indent}  ${v.name.name} = ${v.number},`);
    }
    lines.push(`${indent}}`);
  }
  lines.push('');
}
