import path from 'node:path';
import protobuf from 'protobufjs';
import type { ProtoSchema } from '../runtime/protoFrontend';
import { walkReflection } from '../runtime/protoFrontend';

export interface CodeGenConfig {
  enumStyle: 'enum' | 'union';
  optionalMessageFields: boolean;
  optionalScalarFields: boolean;
  fieldNaming: 'camelCase' | 'preserve';
  oneofStyle: 'optional' | 'union';
}

export const DEFAULT_CONFIG: CodeGenConfig = {
  enumStyle: 'enum',
  optionalMessageFields: true,
  optionalScalarFields: false,
  fieldNaming: 'camelCase',
  oneofStyle: 'optional',
};

const SCALAR_MAP: Record<string, string> = {
  double: 'number', float: 'number',
  int32: 'number', int64: 'number',
  uint32: 'number', uint64: 'number',
  sint32: 'number', sint64: 'number',
  fixed32: 'number', fixed64: 'number',
  sfixed32: 'number', sfixed64: 'number',
  bool: 'boolean', string: 'string', bytes: 'Uint8Array',
};

const SCALAR_TYPES = new Set(Object.keys(SCALAR_MAP));

/**
 * Resolve a type name to the proto file path it's defined in (for import generation).
 * Return null if the type is local (same file) or scalar.
 * 入参为解析后的全限定名(无前导点);类型无法解析时退化为源码中书写的名字。
 */
export type TypeResolver = (typeName: string) => string | null;

/**
 * 生成 filePath 声明的全部 message/enum 的 TS 类型(ADR-0005:输出契约逐字节冻结)。
 * 只输出归属 filePath 的类型(归属以 declarations 为准);跨文件类型经 resolve 生成 import。
 */
export function emit(schema: ProtoSchema, filePath: string, config: CodeGenConfig, resolve?: TypeResolver): string {
  const imports = new Map<string, Set<string>>(); // protoPath → type names
  const lines: string[] = [];

  lines.push('// Generated by proto-utils. Do not edit.');
  lines.push('');

  for (const def of topLevelDefs(schema, filePath)) {
    if (def instanceof protobuf.Type) emitMessage(def, config, resolve, imports, lines, '');
    else emitEnum(def, config, lines, '');
    // services are skipped (out of scope for type generation)
  }

  // Build import statements
  const importLines: string[] = [];
  if (resolve && imports.size > 0) {
    for (const [protoPath, typeNames] of imports) {
      const tsPath = protoPath.replace(/\.proto$/, '');
      const names = [...typeNames].sort();
      importLines.push(`import type { ${names.join(', ')} } from './${tsPath}';`);
    }
    importLines.push('');
  }

  // Combine: header + imports + body
  const header = lines.slice(0, 2);
  const body = lines.slice(2);
  return [...header, ...importLines, ...body].join('\n').trimEnd() + '\n';
}

// ─── Path factories(输出路径与 import 相对路径数学的单一来源)───

export interface OutputPathOptions {
  workspaceRoot: string;
  outputDir: string;
  pathMapping: 'package' | 'file';
}

/** proto 文件绝对路径 → 生成的 .ts 绝对路径。 */
export function createOutputPathResolver(schema: ProtoSchema, options: OutputPathOptions): (protoFile: string) => string {
  const relPathOf = createRelPathResolver(schema, options);
  return (protoFile) => path.join(options.workspaceRoot, options.outputDir, relPathOf(protoFile));
}

/** 基于 declarations 归属构造 TypeResolver:同文件/未知类型返回 null,否则返回相对 import 路径。 */
export function createTypeResolver(schema: ProtoSchema, fromFile: string, options: OutputPathOptions): TypeResolver {
  const relPathOf = createRelPathResolver(schema, options);
  return (typeName) => {
    const target = schema.declarations.get(typeName);
    if (!target || sameFile(target, fromFile)) return null;

    // Relative path from current output to target output
    const fromDir = path.dirname(relPathOf(fromFile));
    let rel = path.relative(fromDir, relPathOf(target)).replace(/\\/g, '/').replace(/\.ts$/, '');
    if (!rel.startsWith('.')) rel = './' + rel;
    return rel;
  };
}

/** schema 是否包含某个 proto 文件(命令层用来拒绝 includeDirs 之外的文件)。 */
export function schemaHasFile(schema: ProtoSchema, filePath: string): boolean {
  return schema.files.some((f) => sameFile(f, filePath));
}

/** proto 文件绝对路径 → 相对 workspaceRoot 的输出 .ts 相对路径(package 或 file 映射)。 */
function createRelPathResolver(schema: ProtoSchema, options: OutputPathOptions): (protoFile: string) => string {
  const packages = packageByFile(schema);
  return (protoFile) => {
    const pkg = packages.get(normalizeFile(protoFile));
    if (options.pathMapping === 'package' && pkg) {
      // package my.service → my/service.ts
      return pkg.replace(/\./g, '/') + '.ts';
    }
    // Use proto file path relative to workspace, swap extension
    return path.relative(options.workspaceRoot, protoFile).replace(/\.proto$/, '.ts');
  };
}

/** 从反射树推导每个 proto 文件的 package(文件内全部顶层类型共享同一条 package 语句)。 */
function packageByFile(schema: ProtoSchema): Map<string, string> {
  const result = new Map<string, string>();
  walkReflection(schema.root, (obj) => {
    if (obj instanceof protobuf.Type || obj instanceof protobuf.Enum || obj instanceof protobuf.Service) {
      const file = declaringFile(schema, obj);
      if (file && !result.has(normalizeFile(file))) {
        let outer: protobuf.ReflectionObject = obj;
        while (outer.parent instanceof protobuf.Type) outer = outer.parent;
        const pkg = outer.parent ? outer.parent.fullName.replace(/^\./, '') : '';
        result.set(normalizeFile(file), pkg);
      }
    }
  });
  return result;
}

// ─── Reflection helpers ──────────────────────────────────────

/** filePath 声明的顶层 message/enum(嵌套类型随父 message 输出),按声明顺序。 */
function topLevelDefs(schema: ProtoSchema, filePath: string): Array<protobuf.Type | protobuf.Enum> {
  const defs: Array<protobuf.Type | protobuf.Enum> = [];
  walkReflection(schema.root, (obj, parent) => {
    if (
      !(parent instanceof protobuf.Type) &&
      (obj instanceof protobuf.Type || obj instanceof protobuf.Enum)
    ) {
      const file = declaringFile(schema, obj);
      if (file && sameFile(file, filePath)) defs.push(obj);
    }
  });
  return defs;
}

function declaringFile(schema: ProtoSchema, obj: protobuf.ReflectionObject): string | undefined {
  return schema.declarations.get(obj.fullName.replace(/^\./, ''));
}

function normalizeFile(p: string): string {
  const n = path.normalize(p);
  return process.platform === 'win32' ? n.toLowerCase() : n;
}

function sameFile(a: string, b: string): boolean {
  return normalizeFile(a) === normalizeFile(b);
}

/** proto3 optional 在 protobufjs 8.x 里表现为合成 oneof `_<field>`(field.proto3Optional 不存在)。 */
function isProto3Optional(field: protobuf.Field): boolean {
  const partOf = field.partOf;
  return partOf != null && partOf.fieldsArray.length === 1 && partOf.name === `_${field.name}`;
}

function isSyntheticOptionalOneof(oneof: protobuf.OneOf): boolean {
  return oneof.fieldsArray.length === 1 && oneof.name === `_${oneof.fieldsArray[0].name}`;
}

// ─── Helpers ─────────────────────────────────────────────────

function toCamelCase(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

function fieldName(name: string, config: CodeGenConfig): string {
  return config.fieldNaming === 'camelCase' ? toCamelCase(name) : name;
}

function isScalar(typeName: string): boolean {
  return SCALAR_TYPES.has(typeName);
}

function baseName(typeName: string): string {
  return typeName.includes('.') ? typeName.split('.').pop()! : typeName;
}

function trackImport(field: protobuf.Field, resolve: TypeResolver | undefined, imports: Map<string, Set<string>>): void {
  if (!resolve || isScalar(field.type)) return;
  // 跨文件归属以解析后的全限定名为准;解析不到(如未 resolveAll)退化为书写名
  const resolved = field.resolvedType;
  const typeName = resolved ? resolved.fullName.replace(/^\./, '') : field.type;
  const protoPath = resolve(typeName);
  if (protoPath) {
    if (!imports.has(protoPath)) imports.set(protoPath, new Set());
    imports.get(protoPath)!.add(baseName(field.type));
  }
}

// ─── Emitters ────────────────────────────────────────────────

function emitMessage(
  msg: protobuf.Type,
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
  lines: string[],
  indent: string,
): void {
  // Nested enums first
  for (const nested of msg.nestedArray) {
    if (nested instanceof protobuf.Enum) {
      emitEnum(nested, config, lines, indent);
      lines.push('');
    }
  }
  // Nested messages
  for (const nested of msg.nestedArray) {
    if (nested instanceof protobuf.Type) {
      emitMessage(nested, config, resolve, imports, lines, indent);
      lines.push('');
    }
  }

  const regularFields = msg.fieldsArray.filter((f) => !f.partOf || isProto3Optional(f));
  const oneofs = msg.oneofsArray.filter((o) => !isSyntheticOptionalOneof(o));

  // Handle oneof as union type
  if (config.oneofStyle === 'union' && oneofs.length > 0) {
    emitMessageWithUnionOneof(msg, regularFields, oneofs, config, resolve, imports, lines, indent);
    return;
  }

  lines.push(`${indent}export interface ${msg.name} {`);

  for (const field of regularFields) {
    lines.push(`${indent}  ${renderField(field, config, resolve, imports)};`);
  }

  // Oneof fields as optional
  for (const oneof of oneofs) {
    for (const field of oneof.fieldsArray) {
      const name = fieldName(field.name, config);
      const type = resolveFieldType(field.type);
      lines.push(`${indent}  ${name}?: ${type};`);
    }
  }

  lines.push(`${indent}}`);
  lines.push('');
}

function emitMessageWithUnionOneof(
  msg: protobuf.Type,
  regularFields: protobuf.Field[],
  oneofs: protobuf.OneOf[],
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
  lines: string[],
  indent: string,
): void {
  // Regular fields as a base interface
  const rendered = regularFields.map((f) => renderField(f, config, resolve, imports));

  // Build union members for each oneof
  for (const oneof of oneofs) {
    const variants: string[] = [];
    for (const field of oneof.fieldsArray) {
      const name = fieldName(field.name, config);
      const type = resolveFieldType(field.type);
      // This variant has this field set, others in the oneof are never
      const othersNever = oneof.fieldsArray
        .filter((f) => f !== field)
        .map((f) => `${fieldName(f.name, config)}?: never`)
        .join('; ');
      variants.push(`{ ${name}: ${type}; ${othersNever} }`);
    }

    if (rendered.length > 0) {
      lines.push(`${indent}export type ${msg.name} = (${rendered.join(' & ')}) & (`);
      lines.push(`${indent}  | ${variants.join(`\n${indent}  | `)}`);
      lines.push(`${indent});`);
    } else {
      lines.push(`${indent}export type ${msg.name} =`);
      lines.push(`${indent}  | ${variants.join(`\n${indent}  | `)};`);
    }
    lines.push('');
  }
}

function renderField(
  field: protobuf.Field,
  config: CodeGenConfig,
  resolve: TypeResolver | undefined,
  imports: Map<string, Set<string>>,
): string {
  const name = fieldName(field.name, config);

  if (field.map) {
    trackImport(field, resolve, imports);
    // protobufjs 运行时 map 字段带 keyType,但 v8 d.ts 未在 Field 上声明 —— 用 in 窄化,不做内联断言
    const keyType = 'keyType' in field && typeof field.keyType === 'string' ? field.keyType : field.type;
    const key = SCALAR_MAP[keyType] ?? keyType;
    const val = resolveFieldType(field.type);
    return `${name}: Record<${key}, ${val}>`;
  }

  trackImport(field, resolve, imports);

  if (field.repeated) {
    return `${name}: ${resolveFieldType(field.type)}[]`;
  }

  // proto3 optional = 显式 presence,恒渲染为 `?`,不受两个 optional 旋钮影响
  const scalar = isScalar(field.type);
  const optional = isProto3Optional(field)
    ? true
    : scalar
      ? config.optionalScalarFields
      : config.optionalMessageFields;
  return `${name}${optional ? '?' : ''}: ${resolveFieldType(field.type)}`;
}

function resolveFieldType(typeName: string): string {
  if (isScalar(typeName)) return SCALAR_MAP[typeName];
  // For cross-file types, use the base name (import handles the rest)
  return baseName(typeName);
}

function emitEnum(
  e: protobuf.Enum,
  config: CodeGenConfig,
  lines: string[],
  indent: string,
): void {
  const values = Object.entries(e.values);
  if (config.enumStyle === 'union') {
    const members = values.map(([name]) => `'${name}'`).join(' | ');
    lines.push(`${indent}export type ${e.name} = ${members};`);
  } else {
    lines.push(`${indent}export enum ${e.name} {`);
    for (const [name, id] of values) {
      lines.push(`${indent}  ${name} = ${id},`);
    }
    lines.push(`${indent}}`);
  }
  lines.push('');
}
