import path from 'node:path';
import protobuf from 'protobufjs';
import type { ProtoSchema } from '../runtime/protoFrontend';
import { walkReflection } from '../runtime/protoFrontend';

export interface CodeGenConfig {
  enumStyle: 'enum' | 'union';
  optionalMessageFields: boolean;
  optionalScalarFields: boolean;
  fieldNaming: 'camelCase' | 'preserve';
  oneofStyle: 'optional' | 'union';
}

export const DEFAULT_CONFIG: CodeGenConfig = {
  enumStyle: 'enum',
  optionalMessageFields: true,
  optionalScalarFields: false,
  fieldNaming: 'camelCase',
  oneofStyle: 'optional',
};

const SCALAR_MAP: Record<string, string> = {
  double: 'number', float: 'number',
  int32: 'number', int64: 'number',
  uint32: 'number', uint64: 'number',
  sint32: 'number', sint64: 'number',
  fixed32: 'number', fixed64: 'number',
  sfixed32: 'number', sfixed64: 'number',
  bool: 'boolean', string: 'string', bytes: 'Uint8Array',
};

const SCALAR_TYPES = new Set(Object.keys(SCALAR_MAP));

/**
 * Resolve a type name to the proto file path it's defined in (for import generation).
 * Return null if the type is local (same file) or scalar.
 * 入参为解析后的全限定名(无前导点);类型无法解析时退化为源码中书写的名字。
 */
export type TypeResolver = (typeName: string) => string | null;

/**
 * 生成 filePath 声明的 message/enum TS 类型与 service 客户端调用接口(0.3.8 起 service 纳入输出契约)。
 * 只输出归属 filePath 的类型(归属以 declarations 为准);跨文件类型经 resolve 生成 import。
 * 0.3.9:跨模块同名 import(或与本地类型同名)按路径段生成确定性别名,消除 TS2300。
 */
export function emit(schema: ProtoSchema, filePath: string, config: CodeGenConfig, resolve?: TypeResolver): string {
  const defs = topLevelDefs(schema, filePath);
  const aliases = buildImportAliases(defs, resolve);
  const imports = new Map<string, Map<string, string>>(); // protoPath → (书写基名 → 可用名)

  /** 类型引用 → 本文件可用名:跨文件类型记录 import(冲突时取别名),本地/未知类型返回书写名基名。 */
  const use: TypeUse = (asWritten, resolvedFqn) => {
    const base = baseName(asWritten);
    const protoPath = resolve?.(resolvedFqn ?? asWritten) ?? null;
    if (!protoPath) return base;
    const display = aliases.get(`${protoPath}\0${base}`) ?? base;
    let byBase = imports.get(protoPath);
    if (!byBase) imports.set(protoPath, (byBase = new Map()));
    byBase.set(base, display);
    return display;
  };

  const lines: string[] = [];
  lines.push('// Generated by proto-utils. Do not edit.');
  lines.push('');

  for (const def of defs) {
    if (def instanceof protobuf.Service) emitService(def, use, lines);
    else if (def instanceof protobuf.Type) emitMessage(def, config, use, lines, '');
    else emitEnum(def, config, lines, '');
  }

  // Build import statements
  const importLines: string[] = [];
  if (imports.size > 0) {
    for (const [protoPath, byBase] of imports) {
      // resolve 返回已带 './'/'../' 前缀的相对路径时直接用,裸路径补 './'(0.3.10 起不再产出 './../x' 双前缀)
      const spec = protoPath.replace(/\.proto$/, '');
      const fromPath = spec.startsWith('.') ? spec : `./${spec}`;
      const names = [...byBase.entries()]
        .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
        .map(([base, display]) => (display === base ? base : `${base} as ${display}`));
      importLines.push(`import type { ${names.join(', ')} } from '${fromPath}';`);
    }
    importLines.push('');
  }

  // Combine: header + imports + body
  const header = lines.slice(0, 2);
  const body = lines.slice(2);
  return [...header, ...importLines, ...body].join('\n').trimEnd() + '\n';
}

/** 类型引用 → 本文件可用名(基名或确定性别名),副作用是记录跨文件 import。 */
type TypeUse = (asWritten: string, resolvedFqn: string | undefined) => string;

/**
 * 预扫描 defs 的全部类型引用,为跨模块同名(或与本地导出同名)的 import 生成确定性别名。
 * 键为 `${protoPath}\0${书写基名}`;别名 = 路径段 PascalCase 拼接 + 基名(如 ProjectGlobalV1ResponseStatus)。
 */
function buildImportAliases(
  defs: Array<protobuf.Type | protobuf.Enum | protobuf.Service>,
  resolve: TypeResolver | undefined,
): Map<string, string> {
  const aliases = new Map<string, string>();
  if (!resolve) return aliases;

  // 本地导出名:顶层类型 + 嵌套类型(随父输出为顶层导出) + service 的 `<Name>Client`
  const localNames = new Set<string>();
  const pathsByBase = new Map<string, Set<string>>();
  const record = (asWritten: string, resolvedFqn: string | undefined): void => {
    if (isScalar(asWritten)) return;
    const protoPath = resolve(resolvedFqn ?? asWritten);
    if (!protoPath) return;
    const base = baseName(asWritten);
    let paths = pathsByBase.get(base);
    if (!paths) pathsByBase.set(base, (paths = new Set()));
    paths.add(protoPath);
  };
  const walkType = (t: protobuf.Type): void => {
    localNames.add(t.name);
    for (const f of t.fieldsArray) record(f.type, f.resolvedType?.fullName.replace(/^\./, ''));
    for (const n of t.nestedArray) {
      if (n instanceof protobuf.Enum) localNames.add(n.name);
      else if (n instanceof protobuf.Type) walkType(n);
    }
  };

  for (const def of defs) {
    if (def instanceof protobuf.Type) walkType(def);
    else if (def instanceof protobuf.Enum) localNames.add(def.name);
    else {
      localNames.add(`${def.name}Client`);
      for (const m of def.methodsArray) {
        record(m.requestType, m.resolvedRequestType?.fullName.replace(/^\./, ''));
        record(m.responseType, m.resolvedResponseType?.fullName.replace(/^\./, ''));
      }
    }
  }

  for (const [base, paths] of pathsByBase) {
    if (paths.size < 2 && !localNames.has(base)) continue;
    for (const protoPath of paths) {
      const segments = protoPath
        .replace(/\.proto$/, '')
        .split('/')
        .filter((s) => s && s !== '.' && s !== '..')
        .map((s) => s.charAt(0).toUpperCase() + s.slice(1));
      aliases.set(`${protoPath}\0${base}`, `${segments.join('')}${base}`);
    }
  }
  return aliases;
}

// ─── Path factories(输出路径与 import 相对路径数学的单一来源)───

export interface OutputPathOptions {
  workspaceRoot: string;
  outputDir: string;
  /** file:相对全部 proto 的公共目录映射目录结构(默认);package:按 package 语句映射目录。 */
  pathMapping: 'package' | 'file';
}

/** proto 文件绝对路径 → 生成的 .ts 绝对路径。 */
export function createOutputPathResolver(schema: ProtoSchema, options: OutputPathOptions): (protoFile: string) => string {
  const relPathOf = createRelPathResolver(schema, options);
  return (protoFile) => path.join(options.workspaceRoot, options.outputDir, relPathOf(protoFile));
}

/** 基于 declarations 归属构造 TypeResolver:同文件/未知类型返回 null,否则返回相对 import 路径。 */
export function createTypeResolver(schema: ProtoSchema, fromFile: string, options: OutputPathOptions): TypeResolver {
  const relPathOf = createRelPathResolver(schema, options);
  return (typeName) => {
    const target = schema.declarations.get(typeName);
    if (!target || sameFile(target, fromFile)) return null;

    // Relative path from current output to target output
    const fromDir = path.dirname(relPathOf(fromFile));
    let rel = path.relative(fromDir, relPathOf(target)).replace(/\\/g, '/').replace(/\.ts$/, '');
    if (!rel.startsWith('.')) rel = './' + rel;
    return rel;
  };
}

/** schema 是否包含某个 proto 文件(命令层用来拒绝 includeDirs 之外的文件)。 */
export function schemaHasFile(schema: ProtoSchema, filePath: string): boolean {
  return schema.files.some((f) => sameFile(f, filePath));
}

/** proto 文件绝对路径 → 相对 outputDir 的输出 .ts 相对路径(package / file 映射)。 */
function createRelPathResolver(schema: ProtoSchema, options: OutputPathOptions): (protoFile: string) => string {
  const packages = options.pathMapping === 'package' ? packageByFile(schema) : null;
  const relRoot = options.pathMapping === 'file' ? commonProtoRoot(schema.files) : null;
  return (protoFile) => {
    if (packages) {
      const pkg = packages.get(normalizeFile(protoFile));
      if (pkg) {
        // package my.service → my/service.ts
        return pkg.replace(/\./g, '/') + '.ts';
      }
    }
    // file:相对全部 proto 的最长公共目录映射——平级 proto 平铺,子目录 proto 保留子结构(common/a/b.proto → a/b.ts)
    return path.relative(relRoot ?? options.workspaceRoot, protoFile).replace(/\.proto$/, '.ts');
  };
}

/** 全部 proto 文件的最长公共目录(file 映射的相对根;win32 比较不分大小写)。 */
function commonProtoRoot(files: string[]): string {
  if (files.length === 0) return '';
  const splitDir = (p: string): string[] => {
    const parts = path.dirname(path.normalize(p)).split(path.sep);
    return process.platform === 'win32' ? parts.map((s) => s.toLowerCase()) : parts;
  };
  const prefix = splitDir(files[0]);
  for (const f of files.slice(1)) {
    const parts = splitDir(f);
    let i = 0;
    while (i < prefix.length && i < parts.length && prefix[i] === parts[i]) i++;
    prefix.length = i;
  }
  return prefix.join(path.sep);
}

/** 从反射树推导每个 proto 文件的 package(文件内全部顶层类型共享同一条 package 语句)。 */
function packageByFile(schema: ProtoSchema): Map<string, string> {
  const result = new Map<string, string>();
  walkReflection(schema.root, (obj) => {
    if (obj instanceof protobuf.Type || obj instanceof protobuf.Enum || obj instanceof protobuf.Service) {
      const file = declaringFile(schema, obj);
      if (file && !result.has(normalizeFile(file))) {
        let outer: protobuf.ReflectionObject = obj;
        while (outer.parent instanceof protobuf.Type) outer = outer.parent;
        const pkg = outer.parent ? outer.parent.fullName.replace(/^\./, '') : '';
        result.set(normalizeFile(file), pkg);
      }
    }
  });
  return result;
}

// ─── Reflection helpers ──────────────────────────────────────

/** filePath 声明的顶层 message/enum/service(message 嵌套类型随父输出),按声明顺序。 */
function topLevelDefs(schema: ProtoSchema, filePath: string): Array<protobuf.Type | protobuf.Enum | protobuf.Service> {
  const defs: Array<protobuf.Type | protobuf.Enum | protobuf.Service> = [];
  walkReflection(schema.root, (obj, parent) => {
    if (
      !(parent instanceof protobuf.Type) &&
      (obj instanceof protobuf.Type || obj instanceof protobuf.Enum || obj instanceof protobuf.Service)
    ) {
      const file = declaringFile(schema, obj);
      if (file && sameFile(file, filePath)) defs.push(obj);
    }
  });
  return defs;
}

/** filePath 是否声明了可生成的顶层 message/enum/service;false(纯 import 聚合文件)时产物只有头部,命令层不落盘。 */
export function hasEmittableTypes(schema: ProtoSchema, filePath: string): boolean {
  return topLevelDefs(schema, filePath).length > 0;
}

function declaringFile(schema: ProtoSchema, obj: protobuf.ReflectionObject): string | undefined {
  return schema.declarations.get(obj.fullName.replace(/^\./, ''));
}

function normalizeFile(p: string): string {
  const n = path.normalize(p);
  return process.platform === 'win32' ? n.toLowerCase() : n;
}

function sameFile(a: string, b: string): boolean {
  return normalizeFile(a) === normalizeFile(b);
}

/** proto3 optional 在 protobufjs 8.x 里表现为合成 oneof `_<field>`(field.proto3Optional 不存在)。 */
function isProto3Optional(field: protobuf.Field): boolean {
  const partOf = field.partOf;
  return partOf != null && partOf.fieldsArray.length === 1 && partOf.name === `_${field.name}`;
}

function isSyntheticOptionalOneof(oneof: protobuf.OneOf): boolean {
  return oneof.fieldsArray.length === 1 && oneof.name === `_${oneof.fieldsArray[0].name}`;
}

// ─── Helpers ─────────────────────────────────────────────────

function toCamelCase(name: string): string {
  return name.replace(/_([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

function fieldName(name: string, config: CodeGenConfig): string {
  return config.fieldNaming === 'camelCase' ? toCamelCase(name) : name;
}

function isScalar(typeName: string): boolean {
  return SCALAR_TYPES.has(typeName);
}

function baseName(typeName: string): string {
  return typeName.includes('.') ? typeName.split('.').pop()! : typeName;
}

/** 字段类型 → TS 类型文本:标量查表,跨文件类型经 use 记录 import 并取可用名。 */
function fieldTypeTs(typeName: string, resolvedFqn: string | undefined, use: TypeUse): string {
  if (isScalar(typeName)) return SCALAR_MAP[typeName];
  return use(typeName, resolvedFqn);
}

// ─── Emitters ────────────────────────────────────────────────

function emitMessage(
  msg: protobuf.Type,
  config: CodeGenConfig,
  use: TypeUse,
  lines: string[],
  indent: string,
): void {
  // Nested enums first
  for (const nested of msg.nestedArray) {
    if (nested instanceof protobuf.Enum) {
      emitEnum(nested, config, lines, indent);
      lines.push('');
    }
  }
  // Nested messages
  for (const nested of msg.nestedArray) {
    if (nested instanceof protobuf.Type) {
      emitMessage(nested, config, use, lines, indent);
      lines.push('');
    }
  }

  const regularFields = msg.fieldsArray.filter((f) => !f.partOf || isProto3Optional(f));
  const oneofs = msg.oneofsArray.filter((o) => !isSyntheticOptionalOneof(o));

  // Handle oneof as union type
  if (config.oneofStyle === 'union' && oneofs.length > 0) {
    emitMessageWithUnionOneof(msg, regularFields, oneofs, config, use, lines, indent);
    return;
  }

  lines.push(`${indent}export interface ${msg.name} {`);

  for (const field of regularFields) {
    lines.push(`${indent}  ${renderField(field, config, use)};`);
  }

  // Oneof fields as optional
  for (const oneof of oneofs) {
    for (const field of oneof.fieldsArray) {
      const name = fieldName(field.name, config);
      const type = fieldTypeTs(field.type, field.resolvedType?.fullName.replace(/^\./, ''), use);
      lines.push(`${indent}  ${name}?: ${type};`);
    }
  }

  lines.push(`${indent}}`);
  lines.push('');
}

function emitMessageWithUnionOneof(
  msg: protobuf.Type,
  regularFields: protobuf.Field[],
  oneofs: protobuf.OneOf[],
  config: CodeGenConfig,
  use: TypeUse,
  lines: string[],
  indent: string,
): void {
  // Regular fields as a base interface
  const rendered = regularFields.map((f) => renderField(f, config, use));

  // Build union members for each oneof
  for (const oneof of oneofs) {
    const variants: string[] = [];
    for (const field of oneof.fieldsArray) {
      const name = fieldName(field.name, config);
      const type = fieldTypeTs(field.type, field.resolvedType?.fullName.replace(/^\./, ''), use);
      // This variant has this field set, others in the oneof are never
      const othersNever = oneof.fieldsArray
        .filter((f) => f !== field)
        .map((f) => `${fieldName(f.name, config)}?: never`)
        .join('; ');
      variants.push(`{ ${name}: ${type}; ${othersNever} }`);
    }

    if (rendered.length > 0) {
      lines.push(`${indent}export type ${msg.name} = (${rendered.join(' & ')}) & (`);
      lines.push(`${indent}  | ${variants.join(`\n${indent}  | `)}`);
      lines.push(`${indent});`);
    } else {
      lines.push(`${indent}export type ${msg.name} =`);
      lines.push(`${indent}  | ${variants.join(`\n${indent}  | `)};`);
    }
    lines.push('');
  }
}

function renderField(field: protobuf.Field, config: CodeGenConfig, use: TypeUse): string {
  const name = fieldName(field.name, config);
  // 跨文件归属以解析后的全限定名为准;解析不到(如未 resolveAll)退化为书写名
  const fqn = field.resolvedType?.fullName.replace(/^\./, '');

  if (field.map) {
    // protobufjs 运行时 map 字段带 keyType,但 v8 d.ts 未在 Field 上声明 —— 用 in 窄化,不做内联断言
    const keyType = 'keyType' in field && typeof field.keyType === 'string' ? field.keyType : field.type;
    const key = SCALAR_MAP[keyType] ?? keyType;
    const val = fieldTypeTs(field.type, fqn, use);
    return `${name}: Record<${key}, ${val}>`;
  }

  if (field.repeated) {
    return `${name}: ${fieldTypeTs(field.type, fqn, use)}[]`;
  }

  // proto3 optional = 显式 presence,恒渲染为 `?`,不受两个 optional 旋钮影响
  const scalar = isScalar(field.type);
  const optional = isProto3Optional(field)
    ? true
    : scalar
      ? config.optionalScalarFields
      : config.optionalMessageFields;
  return `${name}${optional ? '?' : ''}: ${fieldTypeTs(field.type, fqn, use)}`;
}

function emitEnum(
  e: protobuf.Enum,
  config: CodeGenConfig,
  lines: string[],
  indent: string,
): void {
  const values = Object.entries(e.values);
  if (config.enumStyle === 'union') {
    const members = values.map(([name]) => `'${name}'`).join(' | ');
    lines.push(`${indent}export type ${e.name} = ${members};`);
  } else {
    lines.push(`${indent}export enum ${e.name} {`);
    for (const [name, id] of values) {
      lines.push(`${indent}  ${name} = ${id},`);
    }
    lines.push(`${indent}}`);
  }
  lines.push('');
}

/** service → 客户端调用接口 `<Name>Client`:unary 返回 Promise,流式方向用 AsyncIterable 表达(stdlib 无依赖)。 */
function emitService(
  svc: protobuf.Service,
  use: TypeUse,
  lines: string[],
): void {
  lines.push(`export interface ${svc.name}Client {`);
  for (const method of svc.methodsArray) {
    const req = fieldTypeTs(method.requestType, method.resolvedRequestType?.fullName.replace(/^\./, ''), use);
    const res = fieldTypeTs(method.responseType, method.resolvedResponseType?.fullName.replace(/^\./, ''), use);
    const param = method.requestStream ? `AsyncIterable<${req}>` : req;
    const ret = method.responseStream ? `AsyncIterable<${res}>` : `Promise<${res}>`;
    lines.push(`  ${method.name}(request: ${param}): ${ret};`);
  }
  lines.push('}');
  lines.push('');
}
